logging:
  level:
    ROOT: INFO
    com.github.ryanp102694: DEBUG
data.input.dir: "/home/rpelletier/workspace/pubg_ml/erangel_telemetry/squad-fpp"
data.output.dir: "./training_data"

build.training.data: false

prediction.server.url: "http://localhost:5000/batch_predict"
